<?php
/**
 * Web-based Install Wizard
 * Creates DB tables, seeds default data, creates admin account
 */

define('INSTALL_MODE', true);
$configFile = dirname(__DIR__) . '/config.php';
$schemaFile = __DIR__ . '/schema.sql';

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// Step 2: Run install
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbPort = trim($_POST['db_port'] ?? '3306');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass  = $_POST['db_pass'] ?? '';
    $appUrl  = rtrim(trim($_POST['app_url'] ?? ''), '/');
    $jwtSecret = bin2hex(random_bytes(32));
    $adminName  = trim($_POST['admin_name'] ?? 'Admin');
    $adminEmail = trim($_POST['admin_email'] ?? '');
    $adminPass  = $_POST['admin_pass'] ?? '';

    if (!$dbName || !$dbUser || !$adminEmail || !$adminPass || !$appUrl) {
        $error = 'All fields are required.';
    } else {
        try {
            $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
            $pdo = new PDO($dsn, $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]);

            // Run schema (DDL only — stop before seed data)
            $sql = file_get_contents($schemaFile);
            $statements = array_filter(array_map('trim', explode(';', $sql)));
            foreach ($statements as $stmt) {
                if ($stmt) {
                    $pdo->exec($stmt);
                }
            }

            // Seed default data only if tables are empty (prevents duplicates on re-install)
            $deptCount = (int)$pdo->query('SELECT COUNT(*) FROM departments')->fetchColumn();
            if ($deptCount === 0) {
                $pdo->exec("INSERT IGNORE INTO `departments` (`name`, `color`, `sort_order`) VALUES
                    ('UCC+ 9', '#7c3aed', 1),
                    ('UCC Broadband', '#2563eb', 2),
                    ('UCC Hosted', '#059669', 3),
                    ('UCC Leased Line', '#d97706', 4),
                    ('UCC Sales', '#dc2626', 5)");
            }

            $cannedCount = (int)$pdo->query('SELECT COUNT(*) FROM canned_responses')->fetchColumn();
            if ($cannedCount === 0) {
                $pdo->exec("INSERT IGNORE INTO `canned_responses` (`shortcut`, `title`, `content`) VALUES
                    ('hello', 'Greeting', 'Hello! Thank you for contacting us. How can I help you today?'),
                    ('thanks', 'Thank You', 'Thank you for getting in touch! Is there anything else I can help you with?'),
                    ('wait', 'Please Wait', 'Please give me a moment while I look into this for you.'),
                    ('bye', 'Goodbye', 'Thank you for chatting with us today. Have a great day!'),
                    ('ticket', 'Ticket Created', 'I''ve raised a support ticket for you. Our team will follow up via email shortly.')");
            }

            $triggerCount = (int)$pdo->query('SELECT COUNT(*) FROM triggers')->fetchColumn();
            if ($triggerCount === 0) {
                $pdo->exec("INSERT INTO `triggers` (`name`, `type`, `condition_value`, `message`, `is_active`) VALUES
                    ('Welcome Message', 'time', '5', 'Hi there! 👋 Is there anything we can help you with today?', 1),
                    ('Offline Reply', 'offline', NULL, 'Thanks for your message! We''re currently offline but will get back to you as soon as possible. Please leave your email so we can follow up.', 1)");
            }

            // Create admin account
            $hash = password_hash($adminPass, PASSWORD_BCRYPT);
            $stmt = $pdo->prepare("INSERT INTO agents (name, email, password_hash, role, status) VALUES (?, ?, ?, 'admin', 'online') ON DUPLICATE KEY UPDATE role='admin'");
            $stmt->execute([$adminName, $adminEmail, $hash]);

            // Write config.php
            $configContent = <<<PHP
<?php
// ============================================================
// Chat System Configuration
// Generated by installer — edit as needed
// ============================================================

define('DB_HOST', '{$dbHost}');
define('DB_PORT', '{$dbPort}');
define('DB_NAME', '{$dbName}');
define('DB_USER', '{$dbUser}');
define('DB_PASS', '{$dbPass}');

// Full URL to this chat/ directory (no trailing slash)
define('APP_URL', '{$appUrl}');

// Secret key for JWT signing — keep private!
define('JWT_SECRET', '{$jwtSecret}');

// JWT token lifetime in seconds (default 8 hours)
define('JWT_TTL', 28800);

// WhatsApp Cloud API — fill in from Meta Developer Portal
define('WA_PHONE_NUMBER_ID', '');
define('WA_ACCESS_TOKEN', '');
define('WA_VERIFY_TOKEN', '');
define('WA_API_VERSION', 'v18.0');

// CORS: comma-separated allowed origins, or '*' for any
// e.g. 'https://yourwebsite.com,https://www.yourwebsite.com'
define('ALLOWED_ORIGINS', '*');

// Uploads directory (relative to chat/ root)
define('UPLOAD_DIR', __DIR__ . '/uploads/');
define('UPLOAD_URL', APP_URL . '/uploads/');
define('MAX_UPLOAD_MB', 10);
PHP;

            file_put_contents($configFile, $configContent);

            $success = 'Installation complete!';
            $step = 3;
        } catch (Exception $e) {
            $error = 'Installation failed: ' . htmlspecialchars($e->getMessage());
        }
    }
}

// Auto-detect APP_URL
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
$path = dirname(dirname($_SERVER['SCRIPT_NAME'] ?? ''));
$suggestedUrl = $protocol . '://' . $host . rtrim($path, '/');

?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RCG Live Chat — Setup Wizard</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    background: linear-gradient(135deg, #EFF6FF 0%, #DBEAFE 40%, #E0E7FF 100%);
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    padding: 24px 20px;
    -webkit-font-smoothing: antialiased;
    position: relative;
    overflow-x: hidden;
}
body::before {
    content: '';
    position: fixed;
    width: 700px; height: 700px;
    top: -250px; right: -150px;
    background: radial-gradient(circle, rgba(37,99,235,.10), transparent 65%);
    pointer-events: none;
}
body::after {
    content: '';
    position: fixed;
    width: 500px; height: 500px;
    bottom: -150px; left: -100px;
    background: radial-gradient(circle, rgba(99,102,241,.08), transparent 65%);
    pointer-events: none;
}
.card {
    background: #fff;
    border-radius: 20px;
    box-shadow: 0 24px 80px rgba(37,99,235,.13), 0 6px 16px rgba(0,0,0,.06);
    border: 1px solid rgba(37,99,235,.10);
    max-width: 580px;
    width: 100%;
    overflow: hidden;
    position: relative;
    z-index: 1;
}
.card-header {
    background: linear-gradient(135deg, #1D4ED8 0%, #2563EB 60%, #3B82F6 100%);
    padding: 30px 36px 26px;
    color: #fff;
    position: relative;
    overflow: hidden;
}
.card-header::after {
    content: '';
    position: absolute;
    inset: 0;
    background: url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23ffffff' fill-opacity='0.04'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E");
    pointer-events: none;
}
.brand {
    display: flex;
    align-items: center;
    gap: 14px;
    margin-bottom: 20px;
    position: relative;
    z-index: 1;
}
.brand-logo {
    width: 50px; height: 50px;
    border-radius: 13px;
    background: rgba(255,255,255,.18);
    border: 1px solid rgba(255,255,255,.25);
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
    backdrop-filter: blur(8px);
}
.brand-text h1 { font-size: 1.35rem; font-weight: 800; letter-spacing: -.03em; }
.brand-text p { font-size: .74rem; opacity: .72; font-weight: 500; letter-spacing: .06em; text-transform: uppercase; margin-top: 3px; }
.steps {
    display: flex;
    gap: 5px;
    position: relative;
    z-index: 1;
}
.step {
    flex: 1;
    padding: 8px 6px;
    text-align: center;
    border-radius: 8px;
    font-size: .74rem;
    font-weight: 700;
    letter-spacing: -.01em;
    transition: all .2s;
}
.step.active  { background: rgba(255,255,255,.95); color: #1D4ED8; box-shadow: 0 2px 8px rgba(0,0,0,.12); }
.step.done    { background: rgba(255,255,255,.2); color: rgba(255,255,255,.95); }
.step.pending { background: rgba(255,255,255,.08); color: rgba(255,255,255,.45); }
.card-body { padding: 32px 36px 36px; }
.form-group { margin-bottom: 16px; }
label {
    display: block;
    font-size: .68rem;
    font-weight: 700;
    color: #64748B;
    margin-bottom: 6px;
    text-transform: uppercase;
    letter-spacing: .07em;
}
input, select {
    width: 100%;
    padding: 10px 13px;
    border: 1.5px solid #E2E8F0;
    border-radius: 9px;
    font-size: .875rem;
    font-family: inherit;
    color: #0F172A;
    background: #F8FAFC;
    transition: border-color .2s, background .2s, box-shadow .2s;
    outline: none;
}
input:focus, select:focus {
    border-color: #2563EB;
    background: #fff;
    box-shadow: 0 0 0 3px rgba(37,99,235,.10);
}
input::placeholder { color: #CBD5E1; }
.row { display: grid; grid-template-columns: 2fr 1fr; gap: 12px; }
.row-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }
.btn {
    width: 100%;
    padding: 12px;
    background: linear-gradient(135deg, #2563EB, #1D4ED8);
    color: #fff;
    border: none;
    border-radius: 9px;
    font-size: .9rem;
    font-weight: 700;
    cursor: pointer;
    margin-top: 10px;
    transition: all .2s;
    font-family: inherit;
    letter-spacing: -.01em;
    box-shadow: 0 3px 12px rgba(37,99,235,.30);
}
.btn:hover { background: linear-gradient(135deg, #1D4ED8, #1E40AF); box-shadow: 0 5px 18px rgba(37,99,235,.40); transform: translateY(-1px); }
.btn:active { transform: translateY(0); }
.section-label {
    font-size: .65rem;
    font-weight: 800;
    color: #94A3B8;
    text-transform: uppercase;
    letter-spacing: .10em;
    margin-bottom: 14px;
    display: flex;
    align-items: center;
    gap: 8px;
}
.section-label::after { content: ''; flex: 1; height: 1px; background: #E2E8F0; }
.alert {
    display: flex;
    align-items: flex-start;
    gap: 10px;
    padding: 12px 16px;
    border-radius: 10px;
    margin-bottom: 20px;
    font-size: .84rem;
    line-height: 1.5;
}
.alert-error   { background: #FEF2F2; color: #DC2626; border: 1px solid #FECACA; }
.alert-success { background: #F0FDF4; color: #16A34A; border: 1px solid #BBF7D0; }
.divider { border: none; border-top: 1px solid #E2E8F0; margin: 22px 0; }
.check-list {
    background: #F8FAFC;
    border: 1px solid #E2E8F0;
    border-radius: 12px;
    overflow: hidden;
    margin-bottom: 8px;
}
.check-item {
    display: flex;
    align-items: center;
    gap: 12px;
    padding: 11px 16px;
    font-size: .86rem;
    color: #1E293B;
    border-bottom: 1px solid #F1F5F9;
    font-weight: 500;
}
.check-item:last-child { border-bottom: none; }
.check-icon {
    width: 22px; height: 22px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: .7rem;
    font-weight: 800;
    flex-shrink: 0;
}
.icon-ok  { background: #DCFCE7; color: #16A34A; }
.icon-err { background: #FEF2F2; color: #DC2626; }
.check-fail-note { margin-left: auto; font-size: .74rem; color: #EF4444; font-weight: 600; }
.next-steps {
    background: linear-gradient(to bottom, #F8FAFC, #F1F5F9);
    border-radius: 12px;
    padding: 20px 22px;
    margin-top: 20px;
    border: 1px solid #E2E8F0;
}
.next-steps h3 {
    font-size: .88rem;
    font-weight: 800;
    margin-bottom: 16px;
    color: #0F172A;
    display: flex;
    align-items: center;
    gap: 8px;
    letter-spacing: -.02em;
}
.next-steps ol { padding-left: 18px; }
.next-steps li {
    margin-bottom: 12px;
    font-size: .84rem;
    color: #475569;
    line-height: 1.6;
}
.next-steps li strong { color: #1E293B; }
code {
    background: #EFF6FF;
    padding: 2px 7px;
    border-radius: 5px;
    font-size: .79rem;
    font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', monospace;
    word-break: break-all;
    color: #2563EB;
    border: 1px solid #BFDBFE;
    font-weight: 600;
}
a { color: #2563EB; text-decoration: none; }
a:hover { text-decoration: underline; }
.success-banner {
    background: linear-gradient(135deg, #F0FDF4, #DCFCE7);
    border: 1px solid #BBF7D0;
    border-radius: 12px;
    padding: 16px 20px;
    display: flex;
    align-items: center;
    gap: 14px;
    margin-bottom: 20px;
}
.success-icon {
    width: 38px; height: 38px;
    background: #22C55E;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    color: #fff;
    font-size: 1.1rem;
    flex-shrink: 0;
    box-shadow: 0 4px 12px rgba(34,197,94,.3);
}
.success-text strong { display: block; font-size: .92rem; font-weight: 700; color: #15803D; }
.success-text span { font-size: .8rem; color: #4ADE80; font-weight: 500; }
.hint { font-size: .72rem; color: #94A3B8; margin-top: 4px; line-height: 1.5; }
</style>
</head>
<body>
<div class="card">
    <div class="card-header">
        <div class="brand">
            <div class="brand-logo">
                <img src="../dashboard/logo.png" alt="RCG" style="width:32px;height:32px;object-fit:contain;border-radius:7px" onerror="this.style.display='none';this.nextElementSibling.style.display='flex'">
                <svg width="28" height="28" viewBox="0 0 36 36" fill="none" style="display:none">
                    <path d="M18 28 Q18 20 24 20" stroke="white" stroke-width="2.6" stroke-linecap="round"/>
                    <path d="M18 28 Q18 15 27 15" stroke="white" stroke-width="2.6" stroke-linecap="round" opacity=".75"/>
                    <path d="M18 28 Q18 10 30 10" stroke="white" stroke-width="2.6" stroke-linecap="round" opacity=".45"/>
                    <circle cx="18" cy="28" r="2.4" fill="white"/>
                </svg>
            </div>
            <div class="brand-text">
                <h1>RCG Live Chat</h1>
                <p>Rose Communication Group</p>
            </div>
        </div>
        <div class="steps">
            <div class="step <?= $step === 1 ? 'active' : ($step > 1 ? 'done' : 'pending') ?>">
                <?= $step > 1 ? '✓ ' : '' ?>1. Requirements
            </div>
            <div class="step <?= $step === 2 ? 'active' : ($step > 2 ? 'done' : 'pending') ?>">
                <?= $step > 2 ? '✓ ' : '' ?>2. Configure
            </div>
            <div class="step <?= $step === 3 ? 'active' : 'pending' ?>">3. Complete</div>
        </div>
    </div>
    <div class="card-body">

    <?php if ($error): ?>
    <div class="alert alert-error">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" style="flex-shrink:0;margin-top:1px"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/></svg>
        <?= $error ?>
    </div>
    <?php endif; ?>

    <?php if ($step === 1): ?>
    <!-- Step 1: Requirements Check -->
    <?php
    $checks = [
        'PHP 7.4 or higher'  => version_compare(PHP_VERSION, '7.4', '>='),
        'PDO MySQL extension' => extension_loaded('pdo_mysql'),
        'JSON extension'      => extension_loaded('json'),
        'mbstring extension'  => extension_loaded('mbstring'),
        'Root directory writable (config.php)' => is_writable(dirname(__DIR__)) || file_exists($configFile),
        'uploads/ directory writable' => is_writable(dirname(__DIR__) . '/uploads'),
    ];
    $allOk = !in_array(false, $checks, true);
    ?>
    <p style="font-size:.84rem;color:#64748B;margin-bottom:16px;line-height:1.6">
        Checking your server environment before installation.
    </p>
    <div class="check-list">
        <?php foreach ($checks as $label => $ok): ?>
        <div class="check-item">
            <div class="check-icon <?= $ok ? 'icon-ok' : 'icon-err' ?>"><?= $ok ? '✓' : '✗' ?></div>
            <?= htmlspecialchars($label) ?>
            <?php if (!$ok): ?><span class="check-fail-note">Action required</span><?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>
    <?php if ($allOk): ?>
    <a href="?step=2"><button class="btn">Continue to Configuration →</button></a>
    <?php else: ?>
    <div class="alert alert-error" style="margin-top:16px">
        <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" style="flex-shrink:0"><path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z"/></svg>
        Please resolve the failed checks before proceeding.
    </div>
    <?php endif; ?>

    <?php elseif ($step === 2): ?>
    <!-- Step 2: Database + Admin Setup -->
    <form method="POST" action="?step=2">

        <p class="section-label">Database Connection</p>
        <div class="row">
            <div class="form-group">
                <label>Database Host</label>
                <input type="text" name="db_host" value="localhost" required>
            </div>
            <div class="form-group">
                <label>Port</label>
                <input type="text" name="db_port" value="3306" required>
            </div>
        </div>
        <div class="form-group">
            <label>Database Name</label>
            <input type="text" name="db_name" placeholder="e.g. chat_db" required>
        </div>
        <div class="row">
            <div class="form-group">
                <label>Database User</label>
                <input type="text" name="db_user" placeholder="e.g. chat_user" required>
            </div>
            <div class="form-group">
                <label>Database Password</label>
                <input type="password" name="db_pass" placeholder="••••••••">
            </div>
        </div>

        <p class="section-label" style="margin-top:6px">Application</p>
        <div class="form-group">
            <label>App URL <span style="text-transform:none;font-weight:500;letter-spacing:0">(no trailing slash)</span></label>
            <input type="url" name="app_url" value="<?= htmlspecialchars($suggestedUrl) ?>" required>
            <div class="hint">The full URL to your <code>chat/</code> directory, e.g. https://chat.rosecomms.co.uk</div>
        </div>

        <p class="section-label">Admin Account</p>
        <div class="form-group">
            <label>Full Name</label>
            <input type="text" name="admin_name" value="Admin" required>
        </div>
        <div class="form-group">
            <label>Email Address</label>
            <input type="email" name="admin_email" placeholder="admin@rosecomms.co.uk" required>
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" name="admin_pass" placeholder="Minimum 8 characters" minlength="8" required>
        </div>

        <button type="submit" class="btn">Install Now →</button>
    </form>

    <?php elseif ($step === 3): ?>
    <!-- Step 3: Done -->
    <div class="success-banner">
        <div class="success-icon">✓</div>
        <div class="success-text">
            <strong>Installation Successful</strong>
            <span>Your chat system is ready to use</span>
        </div>
    </div>
    <div class="next-steps">
        <h3>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="#2563EB"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg>
            Next Steps
        </h3>
        <ol>
            <li>
                <a href="../dashboard/"><strong>Open your dashboard</strong></a> and sign in with your admin credentials.
            </li>
            <li>
                Go to <strong>Settings → WhatsApp</strong> to enter your Meta Cloud API credentials.
            </li>
            <li>
                Set the webhook URL in your Meta Developer Portal:<br>
                <code><?= htmlspecialchars($suggestedUrl) ?>/api/webhook/whatsapp.php</code>
            </li>
            <li>
                Embed the live chat widget on any webpage:<br>
                <code>&lt;script src="<?= htmlspecialchars($suggestedUrl) ?>/widget/loader.js"&gt;&lt;/script&gt;</code>
            </li>
            <li>
                <strong>Security:</strong> delete or restrict access to the <code>/install/</code> directory once setup is complete.
            </li>
        </ol>
    </div>
    <a href="../dashboard/"><button class="btn" style="margin-top:20px">Open Dashboard →</button></a>
    <?php endif; ?>
</div>
</body>
</html>
