<?php
/**
 * Web-based Install Wizard
 * Creates DB tables, seeds default data, creates admin account
 */

define('INSTALL_MODE', true);
$configFile = dirname(__DIR__) . '/config.php';
$schemaFile = __DIR__ . '/schema.sql';

$step = isset($_GET['step']) ? (int)$_GET['step'] : 1;
$error = '';
$success = '';

// Step 2: Run install
if ($_SERVER['REQUEST_METHOD'] === 'POST' && $step === 2) {
    $dbHost = trim($_POST['db_host'] ?? 'localhost');
    $dbPort = trim($_POST['db_port'] ?? '3306');
    $dbName = trim($_POST['db_name'] ?? '');
    $dbUser = trim($_POST['db_user'] ?? '');
    $dbPass  = $_POST['db_pass'] ?? '';
    $appUrl  = rtrim(trim($_POST['app_url'] ?? ''), '/');
    $jwtSecret = bin2hex(random_bytes(32));
    $adminName  = trim($_POST['admin_name'] ?? 'Admin');
    $adminEmail = trim($_POST['admin_email'] ?? '');
    $adminPass  = $_POST['admin_pass'] ?? '';

    if (!$dbName || !$dbUser || !$adminEmail || !$adminPass || !$appUrl) {
        $error = 'All fields are required.';
    } else {
        try {
            $dsn = "mysql:host={$dbHost};port={$dbPort};dbname={$dbName};charset=utf8mb4";
            $pdo = new PDO($dsn, $dbUser, $dbPass, [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
            ]);

            // Run schema (DDL only — stop before seed data)
            $sql = file_get_contents($schemaFile);
            $statements = array_filter(array_map('trim', explode(';', $sql)));
            foreach ($statements as $stmt) {
                if ($stmt) {
                    $pdo->exec($stmt);
                }
            }

            // Seed default data only if tables are empty (prevents duplicates on re-install)
            $deptCount = (int)$pdo->query('SELECT COUNT(*) FROM departments')->fetchColumn();
            if ($deptCount === 0) {
                $pdo->exec("INSERT IGNORE INTO `departments` (`name`, `color`, `sort_order`) VALUES
                    ('UCC+ 9', '#7c3aed', 1),
                    ('UCC Broadband', '#2563eb', 2),
                    ('UCC Hosted', '#059669', 3),
                    ('UCC Leased Line', '#d97706', 4),
                    ('UCC Sales', '#dc2626', 5)");
            }

            $cannedCount = (int)$pdo->query('SELECT COUNT(*) FROM canned_responses')->fetchColumn();
            if ($cannedCount === 0) {
                $pdo->exec("INSERT IGNORE INTO `canned_responses` (`shortcut`, `title`, `content`) VALUES
                    ('hello', 'Greeting', 'Hello! Thank you for contacting us. How can I help you today?'),
                    ('thanks', 'Thank You', 'Thank you for getting in touch! Is there anything else I can help you with?'),
                    ('wait', 'Please Wait', 'Please give me a moment while I look into this for you.'),
                    ('bye', 'Goodbye', 'Thank you for chatting with us today. Have a great day!'),
                    ('ticket', 'Ticket Created', 'I''ve raised a support ticket for you. Our team will follow up via email shortly.')");
            }

            $triggerCount = (int)$pdo->query('SELECT COUNT(*) FROM triggers')->fetchColumn();
            if ($triggerCount === 0) {
                $pdo->exec("INSERT INTO `triggers` (`name`, `type`, `condition_value`, `message`, `is_active`) VALUES
                    ('Welcome Message', 'time', '5', 'Hi there! 👋 Is there anything we can help you with today?', 1),
                    ('Offline Reply', 'offline', NULL, 'Thanks for your message! We''re currently offline but will get back to you as soon as possible. Please leave your email so we can follow up.', 1)");
            }

            // Create admin account
            $hash = password_hash($adminPass, PASSWORD_BCRYPT);
            $stmt = $pdo->prepare("INSERT INTO agents (name, email, password_hash, role, status) VALUES (?, ?, ?, 'admin', 'online') ON DUPLICATE KEY UPDATE role='admin'");
            $stmt->execute([$adminName, $adminEmail, $hash]);

            // Write config.php
            $configContent = <<<PHP
<?php
// ============================================================
// Chat System Configuration
// Generated by installer — edit as needed
// ============================================================

define('DB_HOST', '{$dbHost}');
define('DB_PORT', '{$dbPort}');
define('DB_NAME', '{$dbName}');
define('DB_USER', '{$dbUser}');
define('DB_PASS', '{$dbPass}');

// Full URL to this chat/ directory (no trailing slash)
define('APP_URL', '{$appUrl}');

// Secret key for JWT signing — keep private!
define('JWT_SECRET', '{$jwtSecret}');

// JWT token lifetime in seconds (default 8 hours)
define('JWT_TTL', 28800);

// WhatsApp Cloud API — fill in from Meta Developer Portal
define('WA_PHONE_NUMBER_ID', '');
define('WA_ACCESS_TOKEN', '');
define('WA_VERIFY_TOKEN', '');
define('WA_API_VERSION', 'v18.0');

// CORS: comma-separated allowed origins, or '*' for any
// e.g. 'https://yourwebsite.com,https://www.yourwebsite.com'
define('ALLOWED_ORIGINS', '*');

// Uploads directory (relative to chat/ root)
define('UPLOAD_DIR', __DIR__ . '/uploads/');
define('UPLOAD_URL', APP_URL . '/uploads/');
define('MAX_UPLOAD_MB', 10);
PHP;

            file_put_contents($configFile, $configContent);

            $success = 'Installation complete!';
            $step = 3;
        } catch (Exception $e) {
            $error = 'Installation failed: ' . htmlspecialchars($e->getMessage());
        }
    }
}

// Auto-detect APP_URL
$protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = $_SERVER['HTTP_HOST'] ?? 'localhost';
$path = dirname(dirname($_SERVER['SCRIPT_NAME'] ?? ''));
$suggestedUrl = $protocol . '://' . $host . rtrim($path, '/');

?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RCG Live Chat — Installer</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0F1724; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; }
body::before { content:''; position:fixed; inset:-50%; background-image: linear-gradient(rgba(192,57,43,.05) 1px,transparent 1px), linear-gradient(90deg,rgba(192,57,43,.05) 1px,transparent 1px); background-size:60px 60px; animation:gridMove 20s linear infinite; pointer-events:none; }
@keyframes gridMove { to { transform:translate(60px,60px); } }
.card { background: #fff; border-radius: 16px; box-shadow: 0 24px 64px rgba(0,0,0,.35); max-width: 560px; width: 100%; overflow: hidden; position: relative; z-index: 1; }
.card-header { background: linear-gradient(135deg, #C0392B, #96281B); padding: 32px 40px 28px; color: #fff; }
.brand { display: flex; align-items: center; gap: 14px; margin-bottom: 16px; }
.brand-logo { width: 52px; height: 52px; border-radius: 14px; background: rgba(255,255,255,.15); display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
.brand-text h1 { font-size: 1.4rem; font-weight: 800; letter-spacing: -.02em; }
.brand-text p { font-size: .78rem; opacity: .7; font-weight: 500; letter-spacing: .05em; text-transform: uppercase; margin-top: 2px; }
.card-body { padding: 32px 40px 40px; }
.steps { display: flex; gap: 6px; margin-bottom: 28px; }
.step { flex: 1; padding: 8px 4px; text-align: center; border-radius: 8px; font-size: .78rem; font-weight: 600; }
.step.active { background: #C0392B; color: #fff; }
.step.done { background: #dcfce7; color: #16a34a; }
.step.pending { background: #f1f5f9; color: #94a3b8; }
.form-group { margin-bottom: 16px; }
label { display: block; font-size: .8rem; font-weight: 600; color: #374151; margin-bottom: 5px; }
input { width: 100%; padding: 10px 12px; border: 1.5px solid #e2e8f0; border-radius: 8px; font-size: .9rem; font-family: inherit; transition: border-color .2s, box-shadow .2s; }
input:focus { outline: none; border-color: #C0392B; box-shadow: 0 0 0 3px rgba(192,57,43,.12); }
.row { display: grid; grid-template-columns: 2fr 1fr; gap: 12px; }
.btn { width: 100%; padding: 12px; background: #C0392B; color: #fff; border: none; border-radius: 8px; font-size: .95rem; font-weight: 700; cursor: pointer; margin-top: 8px; transition: background .2s, transform .1s; font-family: inherit; letter-spacing: .01em; }
.btn:hover { background: #96281B; }
.btn:active { transform: scale(.99); }
.section-label { font-size: .72rem; font-weight: 700; color: #94a3b8; text-transform: uppercase; letter-spacing: .08em; margin-bottom: 14px; }
.alert { padding: 12px 16px; border-radius: 8px; margin-bottom: 20px; font-size: .88rem; }
.alert-error { background: #fef2f2; color: #dc2626; border: 1px solid #fecaca; }
.alert-success { background: #f0fdf4; color: #16a34a; border: 1px solid #bbf7d0; }
.divider { border: none; border-top: 1px solid #e2e8f0; margin: 22px 0; }
.check-item { display: flex; align-items: center; gap: 10px; padding: 9px 0; font-size: .88rem; color: #374151; border-bottom: 1px solid #f1f5f9; }
.check-item:last-child { border-bottom: none; }
.check-item .icon { width: 22px; height: 22px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: .72rem; font-weight: 700; flex-shrink: 0; }
.icon-ok { background: #dcfce7; color: #16a34a; }
.icon-err { background: #fef2f2; color: #dc2626; }
.next-steps { background: #f8fafc; border-radius: 10px; padding: 20px 22px; margin-top: 20px; border: 1px solid #e5e7eb; }
.next-steps h3 { font-size: .95rem; font-weight: 700; margin-bottom: 14px; color: #1e293b; display: flex; align-items: center; gap: 8px; }
.next-steps ol { padding-left: 20px; }
.next-steps li { margin-bottom: 10px; font-size: .86rem; color: #475569; line-height: 1.55; }
code { background: #f1f5f9; padding: 2px 7px; border-radius: 5px; font-size: .81rem; font-family: 'Courier New', monospace; word-break: break-all; color: #C0392B; border: 1px solid #e2e8f0; }
a { color: #C0392B; }
</style>
</head>
<body>
<div class="card">
    <div class="card-header">
        <div class="brand">
            <div class="brand-logo">
                <svg width="34" height="34" viewBox="0 0 36 36" fill="none">
                    <path d="M18 28 Q18 20 24 20" stroke="white" stroke-width="2.6" stroke-linecap="round"/>
                    <path d="M18 28 Q18 15 27 15" stroke="white" stroke-width="2.6" stroke-linecap="round" opacity=".75"/>
                    <path d="M18 28 Q18 10 30 10" stroke="white" stroke-width="2.6" stroke-linecap="round" opacity=".45"/>
                    <circle cx="18" cy="28" r="2.4" fill="white"/>
                </svg>
            </div>
            <div class="brand-text">
                <h1>RCG Live Chat</h1>
                <p>Rose Communication Group</p>
            </div>
        </div>
        <div class="steps">
            <div class="step <?= $step === 1 ? 'active' : ($step > 1 ? 'done' : 'pending') ?>">1. Check</div>
            <div class="step <?= $step === 2 ? 'active' : ($step > 2 ? 'done' : 'pending') ?>">2. Configure</div>
            <div class="step <?= $step === 3 ? 'active' : 'pending' ?>">3. Done</div>
        </div>
    </div>
    <div class="card-body">

    <?php if ($error): ?>
    <div class="alert alert-error"><?= $error ?></div>
    <?php endif; ?>

    <?php if ($step === 1): ?>
    <!-- Step 1: Requirements Check -->
    <?php
    $checks = [
        'PHP >= 7.4' => version_compare(PHP_VERSION, '7.4', '>='),
        'PDO MySQL' => extension_loaded('pdo_mysql'),
        'JSON' => extension_loaded('json'),
        'mbstring' => extension_loaded('mbstring'),
        'config.php writable' => is_writable(dirname(__DIR__)) || file_exists($configFile),
        'uploads/ writable' => is_writable(dirname(__DIR__) . '/uploads'),
    ];
    $allOk = !in_array(false, $checks, true);
    ?>
    <div>
        <?php foreach ($checks as $label => $ok): ?>
        <div class="check-item">
            <div class="icon <?= $ok ? 'icon-ok' : 'icon-err' ?>"><?= $ok ? '✓' : '✗' ?></div>
            <?= htmlspecialchars($label) ?>
            <?php if (!$ok): ?><span style="color:#dc2626;font-size:.8rem;margin-left:auto">Not met</span><?php endif; ?>
        </div>
        <?php endforeach; ?>
    </div>
    <?php if ($allOk): ?>
    <a href="?step=2" style="text-decoration:none"><button class="btn" style="margin-top:24px">Continue to Configuration →</button></a>
    <?php else: ?>
    <div class="alert alert-error" style="margin-top:20px">Please fix the issues above before proceeding.</div>
    <?php endif; ?>

    <?php elseif ($step === 2): ?>
    <!-- Step 2: Database + Admin Setup -->
    <form method="POST" action="?step=2">
        <p class="section-label">Database Connection</p>
        <div class="row">
            <div class="form-group">
                <label>Database Host</label>
                <input type="text" name="db_host" value="localhost" required>
            </div>
            <div class="form-group">
                <label>Port</label>
                <input type="text" name="db_port" value="3306" required>
            </div>
        </div>
        <div class="form-group">
            <label>Database Name</label>
            <input type="text" name="db_name" placeholder="chat_db" required>
        </div>
        <div class="row">
            <div class="form-group">
                <label>Database User</label>
                <input type="text" name="db_user" placeholder="chat_user" required>
            </div>
            <div class="form-group">
                <label>Password</label>
                <input type="password" name="db_pass" placeholder="••••••••">
            </div>
        </div>
        <hr class="divider">
        <p style="font-size:.85rem;color:#64748b;margin-bottom:20px;font-weight:600">APPLICATION</p>
        <div class="form-group">
            <label>App URL (no trailing slash)</label>
            <input type="url" name="app_url" value="<?= htmlspecialchars($suggestedUrl) ?>" required>
        </div>
        <hr class="divider">
        <p style="font-size:.85rem;color:#64748b;margin-bottom:20px;font-weight:600">ADMIN ACCOUNT</p>
        <div class="form-group">
            <label>Full Name</label>
            <input type="text" name="admin_name" value="Admin" required>
        </div>
        <div class="form-group">
            <label>Email Address</label>
            <input type="email" name="admin_email" placeholder="admin@example.com" required>
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" name="admin_pass" placeholder="Min 8 characters" minlength="8" required>
        </div>
        <button type="submit" class="btn">Install Now →</button>
    </form>

    <?php elseif ($step === 3): ?>
    <!-- Step 3: Done -->
    <div class="alert alert-success">✓ Installation completed successfully!</div>
    <div class="next-steps">
        <h3>Next Steps</h3>
        <ol>
            <li>Open <a href="../dashboard/">your dashboard</a> and log in with your admin credentials.</li>
            <li>Go to <strong>Settings → WhatsApp</strong> to configure your WhatsApp Cloud API credentials.</li>
            <li>Set your webhook URL in the Meta Developer Portal:<br>
                <code><?= htmlspecialchars($suggestedUrl) ?>/api/webhook/whatsapp.php</code>
            </li>
            <li>Embed the widget on your website:<br>
                <code>&lt;script src="<?= htmlspecialchars($suggestedUrl) ?>/widget/loader.js"&gt;&lt;/script&gt;</code>
            </li>
            <li><strong>Delete or protect the <code>/install/</code> directory</strong> after setup.</li>
        </ol>
    </div>
    <a href="../dashboard/" style="text-decoration:none"><button class="btn" style="margin-top:20px">Go to Dashboard →</button></a>
    <?php endif; ?>
</div>
</body>
</html>
